name: Compile Android Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Lets you trigger compilation manually!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b

    - name: Compile libentityculler.so
      run: |
        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++ \
          -shared -fPIC -std=c++20 \
          -I./src \
          src/main.cpp \
          -o libentityculler.so \
          -llog

    - name: Package Mod into Zip
      run: |
        zip -r EntityCuller.levipack.zip libentityculler.so manifest.json

    - name: Upload Finished Mod File
      uses: actions/upload-artifact@v4
      with:
        name: EntityCuller-Plugin
        path: EntityCuller.levipack.zip
